### ISSUE TITLE
ACL pdf files

### ISSUE THREAD

**Issue by mayq97** [iamjanvijay/acl-cite-net#1]
This is a good dataset about ACL, could you please make the downloadable PDF file public?

**Comment by iamjanvijay** [comment]
you can download them by yourself using the following command: 
`git clone https://github.com/iamjanvijay/acl-cite-net.git; cd acl-cite-net/dataset/; python code/main.py --download_pdfs; cd downloads/pdfs/; `
As the above command finished its execution, you'll be in the folder with all the PDFs.

**Comment by mayq97** [comment]
The number of ACL papers is huge and it would be great if the downloaded pdf could be shared directly.
It takes a long time to re-download pdf files.
